### ISSUE TITLE
Requiring module from Node-webkit : "Module did not self-register"

### ISSUE THREAD

**Issue by sgaze** [agnat/node_mdns#101]
I'm trying to load mode_mdns from node-webkit 0.10.5 (based on Node v0.11.13, Chromium 35.0.1916.157) with this simple javascript line :

```
var mdns = require('mdns');
```

I get this result:

```
[9084:1103/094449:INFO:CONSOLE(1)] ""process.mainModule.filename: /index.html"", source: process_main (1)
[9084:1103/094449:INFO:CONSOLE(35)] "Uncaught Error: Module did not self-register.", source: /home/sgaze/dev/local/nw-sp/node_modules/mdns/lib/dns_sd.js (35)
```

I have to say that it works with node-webkit 0.8.6 (based on Node v0.10.22, Chrome 30.0.1599.66)

**Comment by shaundon** [comment]
I know this hasn't been updated for a while, but I came up against this issue recently. Here's how I worked around it:

1. I made sure to use node-webkit 0.8.6 (Previously I was on 0.12.0-alpha2).
2. Installed nw-gyp globally with `npm install -g nw-gyp`.
3. I added a postinstall script to my package.json to rebuild mdns with nw-gyp after it installs:

```JSON
  "scripts": {
    "postinstall": "cd node_modules/mdns && nw-gyp configure --target=0.8.6 && nw-gyp build && cd ../..",
    "postupdate": "cd node_modules/mdns && nw-gyp configure --target=0.8.6 && nw-gyp build && cd ../.."
  }
```

It isn't the most elegant solution, but it's doing the trick for me.

**Comment by acidhax** [comment]
I need more specific information on what exactly works. This discussion is all over the place.

Node version.
Node-Webkit version.
Configure flags.

**Comment by y-lohse** [comment]
It's all over the place because there's a stupid long list of factors that come into play. Most of the issues are because someone missed a bit of documentation — but to be fair there are lots of them.

*It definitely works* on Windows 7 & OsX using node 0.11.x and node-webkit 0.11.x Probably Linux too but haven't tested. But mdns needs to be rebuilt using nw-gyp and both node & node-webkit need to use the same architecture. And on Windows the binary needs to be called `nw.exe`. Maybe there are other caveats I'm forgetting about but really everything is documented somewhere.

**Comment by acidhax** [comment]
So,
Node v0.11.x
Node-Webkit v0.11.x

npm install mdns
./node_modules/mdns nw-gyp rebuild (with no flags?)

**Comment by acidhax** [comment]
Downloaded: nw-v0.11.5, node-v0.11.5
npm install mdns
test/node_modules/mdns> nw-gyp configure --arch=ia32 --version=v0.11.5
test/node_modules/mdns> nw-gyp build
test>nw-v0.11.5\nw.exe .


Working.

**Comment by sgaze** [comment]
Downloaded nw v0.11.6

git clone http://github.com/agnat/node_mdns mdns
nw-gyp configure --target=0.11.6
nw-gyp build

Working on Windows 7 directly

Working too on Ubuntu 64bits but had to disable ipv6 discovery to find devices:
`var sequence = [
          mdns.rst.DNSServiceResolve()
        , mdns.rst.getaddrinfo({'families':[4]})
        , mdns.rst.makeAddressesUnique()
      ];
var browser = mdns.createBrowser(mdns.tcp('http'), {resolverSequence: sequence});`

**Comment by drasko** [comment]
Tried with v0.11.6 and latest nw from npm on Debian Linux x64.

Still getting error:
[25725:0208/052705:INFO:CONSOLE(35)] "Uncaught Error: Module did not self-register.", source: /home/drasko/nw/test/node_modules/mdns/lib/dns_sd.js (35)
[25725:0208/052705:ERROR:nw_shell.cc(324)] TypeError: Cannot read property 'createBrowser' of undefined


I tied with default mdns from npm and the one from the master branch

**Comment by mangaga** [comment]
hi, everyone.  @ghostoy  @rongerwang

some of my users got the error "Module did not self-register." just sometimes  when they access the app's local sqlite3 database(node-sqlite3) on nwjs, but some of users did never got this and never did myself.  And never got this error access by node.js v4.x and v5.x.

Who can tell me why? What the true problem is？ thanks all.

test on computer environments : 
window xp & WIN7 32bit & WIN7 64 bit
both nw0.12.3  node.js v4.x node-sqlite3 v3.1.x  node-sqlite3 rebuilded by nw-gyp
nw0.13.x - nw0.14.x   node.js v5.x and  node-sqlite3 v3.1.x  node-sqlite3 rebuilded by node-gyp

.node path for nw0.14.x   and node.js v5.x
.node path:
path\app\node_modules\sqlite3\lib\binding\node-v47-win32-ia32\node_sqlite3.node
path\app\node_modules\sqlite3\lib\binding\node-v47-win32-x64\node_sqlite3.node

nw0.12.3
.node path for node.js v4.x (never got this error):
path\app\node_modules\sqlite3\lib\binding\node-v46-win32-ia32\node_sqlite3.node
path\app\node_modules\sqlite3\lib\binding\node-v46-win32-x64\node_sqlite3.node
.node path for nwjs v0.12.3:
path\app\node_modules\sqlite3\lib\binding\node-webkit-v0.12.3-win32-ia32\node_sqlite3.node
path\app\node_modules\sqlite3\lib\binding\node-webkit-v0.12.3-win32-x64\node_sqlite3.node
