### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by christomitov** [agnat/node_mdns#119]
Hi,

I'm trying to use mdns with node-webkit on Windows. I have tried both installation methods (npm install and also pulling down the latest and linking).

I have tried a vanilla install but get this error. Then I tried using `nw-gyp configure --target=0.10.5 --target-arch=ia32`  to specifically target the node webkit version and architecture I want. Again, same issue. 

This is on Windows 7 with node 0.11.3 and node webkit 0.10.5. Below is a stack trace I get inside node webkit:

```
Error: The specified module could not be found.
C:\Users\build\AppData\Local\Temp\nw8680_21392\node_modules\mdns\build\Release\dns_sd_bindings.node
    at Error (native)
    at Module.load (module.js:354:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object. (C:\Users\build\AppData\Local\Temp\nw8680_21392\node_modules\mdns\lib\dns_sd.js:24:20)
    at Module._compile (module.js:454:26)
    at Object.Module._extensions..js (module.js:472:10)
    at Module.load (module.js:354:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
```

**Comment by agnat** [comment]
Since it does not find the module I assume the build fails...

1. Did you follow the [installation instructions](https://github.com/agnat/node_mdns#installation)?
2. Please [gist](https://gist.github.com) the full compiler output.

**Comment by christomitov** [comment]
1. Yes. I have the Bonjour SDK installed properly and the Bonjour Home env variable set as well.
2. [Here you go](https://gist.github.com/christomitov/94e90ff7f1609496ff72)

Just to clarify, "npm test" passes successfully so I think the module is compiled properly.

**Comment by agnat** [comment]
Indeed, it builds just fine. No clue then... other than that it is probably $something with node-webkit and native modules. :-/

Maybe @y-lohse has an idea? AFAIK he has a setup similar to yours.

**Comment by christomitov** [comment]
Ugh, I figured it out. According to [this](https://github.com/nwjs/nw.js/issues/199) it's an old bug with node webkit. The executable actually needs to be named nw.exe to find the modules properly, I was renaming it in my grunt task to the actual app name.

Sorry for this @agnat

**Comment by agnat** [comment]
NP. Glad you figured it out.
