### ISSUE TITLE
Can't detect disconnect of devices

### ISSUE THREAD

**Issue by joelongstreet** [agnat/node_mdns#124]
First - sorry, I'm kind of new to mdns and networking in general. I'm attempting to detect when devices join and leave the network, but can't seem to get it figured out.

Why won't the below work? As I add and remove devices, I don't see any difference in the output from the logs. Even if the devices aren't connected to the network, i see the log with it's name and id.

Thanks for any help you can provide.

    var mdns = require('mdns');
    var browser = null;

    var startBrowser = function(){
      console.log('--------');
      if(browser) browser.stop();

      setTimeout(function(){
        browser = mdns.createBrowser(mdns.tcp('googlecast'));

        browser.on('serviceUp', function(service){
          console.log('chromecast detected -', service.name, service.txtRecord.id);
        });

        browser.on('serviceDown', function(service){
          console.log('chromecast lost', service);
        });

        browser.start();
      }, 1000);
    };

    startBrowser();
    setInterval(startBrowser, 5000);

**Comment by agnat** [comment]
Kind of hard to say...

First, why do you mess around with timeouts and intervals? Just start one browser instance. Second, the `serviceDown` events have quite a long timeout. This is per spec and AFAIK there is no way to adjust that.

HTH

**Comment by joelongstreet** [comment]
I was using an interval to try and detect new items on the network and if one has left the network. If I use the code below, I don't get notified of new devices and I don't get notified if a device has left the network.

    var mdns = require('mdns');
    var browser = mdns.createBrowser(mdns.tcp('googlecast'));

    browser.on('serviceUp', function(service){
      console.log('chromecast detected -', service.name, service.txtRecord.id);
    });

    browser.on('serviceDown', function(service){
      console.log('chromecast lost', service);
    });

    browser.start();

**Comment by agnat** [comment]
These two scripts work for me:

#### Browser

````
var mdns = require('mdns');
var browser = mdns.createBrowser(mdns.tcp('googlecast'));

browser.on('serviceUp', function(service){
  console.log('serviceUp ', service);
});

browser.on('serviceDown', function(service){
  console.log('serviceDown', service);
});

browser.start();
````

#### Advertisement

````
var mdns = require('mdns')
  , ad = mdns.createAdvertisement(mdns.tcp('googlecast'), 8888);

ad.start();
````

So, I suspect a local problem. Could be a network or system configuration issue or a bug on the advertising side. As I said: Hard to say...

**Comment by joelongstreet** [comment]
Oh weird... this works perfectly and almost instantaneously if i run an advertiser and a browser. Definitely appears to be an issue with the ChromeCasts. I'll investigate and post my findings.
