### ISSUE TITLE
DNSServiceGetAddrInfo undefined reference in ubuntu

### ISSUE THREAD

**Issue by pmuvva** [agnat/node_mdns#139]
Hi,

I am trying to port Airplay code in UBUNTU with AVAHI interface. But it is not able find DNSServiceGetAddrInfo definition. Please help me how to resolve this issue?

Thanks,
Muvva.

**Comment by agnat** [comment]
Indeed `DNSServiceGetAddrInfo` does not exist on avahi. If it is still being called that's probably $someone messing with the [resolver sequence](http://agnat.github.io/node_mdns/user_guide.html#resolver_sequence).

Good luck.

**Comment by pmuvva** [comment]
In that case shall I port DNSServiceGetAddrInfo from dnssd_ipc.c  open source from apple. I am the beginner. Please guide me.

**Comment by agnat** [comment]
> In that case shall I port DNSServiceGetAddrInfo from dnssd_ipc.c

lol... No! There already is support to resolve addresses on avahi systems. It's just that `$something` on your end (probably the application you are porting) breaks that support. The most likely candidate is that it messes with the resolver chain.

> Please guide me.

1. Read about the resolver chain
2. Note that the default chain is different for avahi and mac os
3. Look at the resolver chain of the app you are porting
4. Fix it to do the right thing

There you go.

**Comment by pmuvva** [comment]
Thanks a lot. 
I am trying to run Apple Airplay receiver directly in ubuntu other than I haven't done anything.

**Comment by agnat** [comment]
Yeah... but...

> I am trying to run Apple Airplay receiver

I have no idea what that is... and to be honest, I'm not sure I want to know.

The thing is: You haven't provided any information on what you are actually trying to do. No commands, no source code, no console logs. Just a few buzzwords in CAPITALS. So, I'm having a hard time helping.

Also, I'm not actually here to _teach_ you this stuff. You are the beginner. You'll have to do your own learning...
