### ISSUE TITLE
Incomplete mDNS response on Windows 8.1 Pro

### ISSUE THREAD

**Issue by GoRadioGo** [agnat/node_mdns#143]
Windows 8.1 Pro 64-bit
Visual Studio 2015 Community

Run simple javascript example just to test browseThemAll() functionality.

> var mdns = require('mdns');
> // Create mDNS object to monitor all services ...
> var mDnsDiscover = mdns.browseThemAll();
> // Expect a mDNS event that looks something like the following:
> //{
> //    interfaceIndex: 4
> //, name: 'somehost'
> //    , networkInterface: 'en0'
> //    , type: { name: 'http', protocol: 'tcp', subtypes: []}
> //, replyDomain: 'local.'
> //, fullname: 'somehost._http._tcp.local.'
> //, host: 'somehost.local.'
> //, port: 4321
> //, addresses: [ '10.1.1.50', 'fe80::21f:5bff:fecd:ce64' ]
> //}
> mDnsDiscover.on('serviceUp', function (service) {
>     console.log("service up: ", service);
> });

Instead we are seeing typical response would be as follows:

> service up:  { interfaceIndex: 3,
>   type: { name: 'googlecast', protocol: 'tcp', subtypes: [] },
>   replyDomain: '.',
>   flags: 3,
>   networkInterface: 'Wi-Fi' }

Not clear to me why we are not seeing a replyDomain or port value.

Using an existing Windows mDNS executable, the results are as follows:
<img width="306" alt="windows exe mdns results" src="https://cloud.githubusercontent.com/assets/11307556/10178983/6543fa12-66c0-11e5-9b64-158db916a81e.png">

When I installed via 'npm install mdns --save ', it performed successfully, but with various compiler warnings. See attached log file at end of this issue. Not sure if these compiler warnings are related to the issue we are seeing.
# 

> Registry url: https://registry.npmjs.org/
> Current Time: 2015-09-29 2:11:29 PM
> Last Refreshed: 2015-09-29 11:29:58 AM
> Number of Results: 201042
> ====Executing command 'npm install mdns --save '====
> 
> mdns@2.2.10 install D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns
> node-gyp rebuild
> D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   dns_sd.cpp
>   dns_service_browse.cpp
>   dns_service_enumerate_domains.cpp
>   dns_service_get_addr_info.cpp
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\dns_service_browse.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\dns_sd.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\dns_service_get_addr_info.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\dns_service_enumerate_domains.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
>   dns_service_process_result.cpp
>   dns_service_ref.cpp
>   dns_service_ref_deallocate.cpp
>   dns_service_ref_sock_fd.cpp
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\dns_service_ref_sock_fd.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\dns_service_ref_deallocate.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\dns_service_process_result.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\dns_service_ref.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
>   dns_service_register.cpp
>   dns_service_resolve.cpp
>   mdns_utils.cpp
>   network_interface.cpp
> ..\src\dns_service_register.cpp(122): warning C4267: '=': conversion from 'size_t' to 'uint16_t', possible loss of data [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\dns_service_register.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\mdns_utils.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\dns_service_resolve.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
>   socket_watcher.cpp
>   txt_record_ref.cpp
>   txt_record_create.cpp
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\network_interface.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
>   txt_record_deallocate.cpp
> ..\src\txt_record_create.cpp(29): warning C4267: '=': conversion from 'size_t' to 'uint16_t', possible loss of data [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\socket_watcher.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\txt_record_ref.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\txt_record_create.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
>   txt_record_set_value.cpp
>   txt_record_get_length.cpp
>   txt_record_buffer_to_object.cpp
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\txt_record_deallocate.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> ..\src\txt_record_set_value.cpp(44): warning C4267: 'argument': conversion from 'size_t' to 'uint8_t', possible loss of data [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> ..\src\txt_record_buffer_to_object.cpp(28): warning C4267: 'argument': conversion from 'size_t' to 'uint16_t', possible loss of data [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> ..\src\txt_record_buffer_to_object.cpp(35): warning C4267: 'argument': conversion from 'size_t' to 'uint16_t', possible loss of data [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\txt_record_get_length.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\txt_record_set_value.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ..\src\txt_record_buffer_to_object.cpp) [D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\dns_sd_bindings.vcxproj]
>      Creating library D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\Release\dns_sd_bindings.lib and object D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\Release\dns_sd_bindings.exp
>   Generating code
>   Finished generating code
>   dns_sd_bindings.vcxproj -> D:\Documents\xxx-Software\yyy\RestTest\node_modules\mdns\build\Release\dns_sd_bindings.node
> mdns@2.2.10 node_modules\mdns
> ├── bindings@1.2.1
> └── nan@2.0.9

====npm command completed with exit code 0====

**Comment by agnat** [comment]
Apologies for the late response.

It looks like address resolution is broken on this system. I know the module works fine on various versions of windows as long as the mdns responder service is healthy. If the problem persists after reboot I'd try to reinstall the bonjour sdk.
