### ISSUE TITLE
Snow Leopard compatibility (old version of GCC)

### ISSUE THREAD

**Issue by fahrvergnuugen** [agnat/node_mdns#150]
I have a very old Mac Mini which has been employed as my home media server for the past 8 years. Unfortunately, I cannot upgrade the OS past Snow Leopard, however it still does it's job as a webserver and iTunes server perfectly fine.

I was really hoping to run [homebridge](https://github.com/nfarina/homebridge) on it, however homebridge relies on node_mdns and I cannot get node_mdns to install.

I should mention that I have the command line developer tools from Lion 10.7 installed (which makes GCC available).

Here's what happens:

```
npm -g install mdns

> mdns@2.2.11 install /usr/local/lib/node_modules/mdns
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:
In file included from ../src/mdns.hpp:12:
../node_modules/nan/nan.h:41:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
# error This version of node/NAN/v8 requires a C++11 compiler
  ^
1 error generated.
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 10.8.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/mdns
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 10.8.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "mdns"
npm ERR! node v4.2.3
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.2.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.2.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/npm-debug.log
```

the line:
```
../node_modules/nan/nan.h:41:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
```
indicates to me that the problem is with the version of GCC that I have available on my machine. Is there any way to get mdns to compile with an older version of GCC?

Here's the output of `gcc --version`:
```
i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.9.00)
```

**Comment by agnat** [comment]
> I have a very old Mac Mini which has been employed as my home media server for the past 8 years. 

Awesome. Let's see...

> [...] indicates to me that the problem is with the version of GCC that I have available on my machine.

That's right. However, it is not node_mdns or NAN that requires a modern compiler, but upstream packages, notably v8 itself.

I see a couple of options. None is totally straight forward. So your milage may vary.

1. Use an older version of node that does not require C++11. Node v0.12 should work out of the box.
1. Compile node_mdns on a modern Mac and copy the binary. This is drastic and might just not work. But node_mdns does not link to anything except libc and it's worth a try.
1. Compile on a modern Mac but use the old runtime environment. This requires fiddling with the taps, possibly by hacking the generated Makefiles
1. If brew or macports is an option you might just install a more modern compiler. If it is not you still could compile a modern compiler from scratch.

Hope this helps.

**Comment by fahrvergnuugen** [comment]
@agnat Thanks a ton for the suggestions. 

Option 2 seems really straight forward so I gave it a go. I compiled on my OSX 10.9 laptop then copied the node_modules/mdns directory to my mac mini.

Here's what happens when I try the test script:

```
mini:bonjourjs paul$ node test.js 
/Users/paul/Desktop/bonjourjs/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/paul/Desktop/bonjourjs/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

**Comment by agnat** [comment]
Hehe... You need to use the same node version (major.minor) on host and target.

;)

**Comment by fahrvergnuugen** [comment]
Ahhh! Thats the first time ive seen that one. Thanks for being gentle in pointing out my n00bness ;)

**Comment by agnat** [comment]
No worries. Like I said...

> None is totally straight forward.

**Comment by fahrvergnuugen** [comment]
Success with option 2!
Thanks again. My mac mini zombie lives on...

**Comment by amiblau** [comment]
Any chance that you could share your snow leopard binary and some insight on installation?

**Comment by fahrvergnuugen** [comment]
@amiblau I would love to help. Bear in mind I'm not a nodeJS or NPM expert, but I will do my best to explain how I got mdns to run on Snow Leopard. These instructions will explain how to do a global install of the module.

If you have a modern mac, you can compile mdns on it and then copy the compiled binary to your snow leopard machine. As I found out, this **only** works if you have the exact same version of NodeJS installed on both machines!

## If you have two macs:

1. Open a terminal window on both macs and and run ``node --version``. **Verify that the NodeJS version  on both machines are the same.** If they are not the same you will get the ``Error: Module version mismatch. Expected ##, got ##.``` error when you try to use the manually copied module on the snow leopard machine. If your versions are not the same, go to NodeJS.org and download the installer for the later of the two versions you have (at this writing I am able to use NodeJS version 5.2.0 on Snow Leopard.
1. Next install & compile mdns on your *modern mac*: `npm -g install mdns`. This should create a folder `/usr/local/lib/node_modules/mdns/` which contains the compiled mnds module.
1. Now copy `/usr/local/lib/node_modules/mdns/` from your *modern mac* to the same directory on your *snow leopard mac*. You can do this from the command line on your modern mac with `scp -r /usr/local/lib/node_modules/mdns/ youruser@snowleopard_machine_address:/usr/local/lib/node_modules/`
1. Switch over to your Snow Leopard Mac and check to make sure the mdns folder (and it's contents) are in `/usr/local/lib/node_modules/`


## If all you have is a Snow Leopard Mac

1. Install NodeJS [version 5.2.0] (https://nodejs.org/dist/v5.2.0/node-v5.2.0.pkg)
1. Download my precompiled binary: 
[mdns-2.2.11_node-5.2.0_snow_leopard.tar.gz](https://github.com/agnat/node_mdns/files/92936/mdns-2.2.11_node-5.2.0_snow_leopard.tar.gz)
1. Unzip it in your `/usr/local/lib/node_modules` directory.


I hope this helps!

**Comment by amiblau** [comment]
@fahrvergnuugen Thanks so much for this info I will not have any time to look into this until this coming weekend.  I did successfully get homebridge working on my laptop so I know it can be done.  I will attempt to do either method soon.  This gives me hope that my Xserve 1,1 still has some life left  It rocks as a Plex server,  print server, Music dock, as well as many other little things around the house.  If it can be a "HomeKit bridge" as well now we are talking

**Comment by fahrvergnuugen** [comment]
@amiblau no problem. Your mac zombie is way cooler than mine! ;)

**Comment by amiblau** [comment]
I got it working! thanks so much for your help @fahrvergnuugen.  I didn't even have to take down the server while my wife was using Plex.
