### ISSUE TITLE
mdns suddenly stopped working (Windows)

### ISSUE THREAD

**Issue by black-snow** [agnat/node_mdns#151]
I had *node_mdns* set up and working just fine. Today I tried to start my application and it errors out with this:
![mdns_error](https://cloud.githubusercontent.com/assets/579733/12168760/ad044fce-b534-11e5-982f-bda1e01aea3a.PNG)

I tried to `npm uninstall` and re-install mdns without success.

> Unexpected result while probing for avahi: { [Error: dns service error: unknown error code] errorCode: -65563 }
> App threw an error when running [Error: DNSServiceRef is not initialized]

*avahi.js:28* is this: `dns_sd.DNSServiceRefDeallocate(sr);`

**Comment by agnat** [comment]
Hm. I'm afraid I'm not overly familiar with the behavior on windows. Since it was working before...

Is the bonjour service (from the SDK) up and running? Maybe it crashed? ... or $something messed with the installation? Maybe restart/reinstall _that_?

Hope this helps.

**Comment by black-snow** [comment]
After I restarted my machine it works fine again ... jesus. Seems like, indeed, the bonjour service crashed or didn't start at all.
This https://photosync-app.com/photosync/en/help/companion-win/answers/photosync-companion-reports-a-dnsservicebrowse-error-65563-what-can-i-do.html helped.

@agnat thanks for the quick reply.
