### ISSUE TITLE
Unkown DNS service error

### ISSUE THREAD

**Issue by kevinkleine** [agnat/node_mdns#153]
Hi all,

First off, super cool lib! I'm using it all the time. 

Issue: every once in a while I get the error below and I don't know why. The error disappears on its own after reboot, or sometimes just after restarting the app a couple of times. 

    Error: dns service error: unknown
        at Error (native)
        at MDNSService.on_resolver_done (/3dea/node_modules/mdns/lib/resolver_sequence_tasks.js:19:30)
        at SocketWatcher.MDNSService.self.watcher.callback (/3dea/node_modules/mdns/lib/mdns_service.js:18:40)

Any ideas?

**Comment by ronkorving** [comment]
This has to be the most frustrating error in all Node libraries I've ever used. And truth be told, it doesn't originate in this library at all. There really should be no such as thing as "unknown error". Maybe avahi needs some work.

**Comment by agnat** [comment]
Hi @kevinkleine,

> First off, super cool lib!

Thanks!

> Any ideas?

@ronkorving is right. Unfortunately there is no _good_ solution. Try this:

 * trap the error using an error handler
 * if it happens stop your browser and wait a second
 * create and start a new browser
 * rinse and repeat

Obviously this only helps with a temporary outage, not if a reboot is required :-/

For completeness there is a more radical solution: Depending on your requirements and environment it might be possible to just deinstall avahi and use apples mdns responder instead. I haven't tested this in a long time. So, the ... uh... "auto detection" might need a little kick.

Hope this helps.

**Comment by istiti** [comment]
same error here 

![image](https://user-images.githubusercontent.com/2789203/35556159-cd7e267a-05a1-11e8-98a2-6194c2b1a2c9.png)


get this after running this script https://github.com/williamkapke/ipp/blob/master/examples/findPrinters.js

any help here ?
