### ISSUE TITLE
Failed at the mdns@2.3.1 install script

### ISSUE THREAD

**Issue by mimi89999** [agnat/node_mdns#160]
I'm trying to install mdns as a node dependency of Kaku. When I run "npm i" I get this error:

> mdns@2.3.1 install /home/michel/git/Kaku/node_modules/mdns
> node-gyp rebuild

make : on entre dans le répertoire « /home/michel/git/Kaku/node_modules/mdns/build »
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: Aucun fichier ou dossier de ce type
compilation terminated.
dns_sd_bindings.target.mk:145 : la recette pour la cible « Release/obj.target/dns_sd_bindings/src/dns_sd.o » a échouée
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Erreur 1
make : on quitte le répertoire « /home/michel/git/Kaku/node_modules/mdns/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.3.0-1-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/michel/git/Kaku/node_modules/mdns
gyp ERR! node -v v5.7.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! mdns@2.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.1 install script.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! cwd /home/michel/git/Kaku
npm ERR! node -v v5.7.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/michel/git/Kaku/npm-debug.log
npm ERR! not ok code 0

OS: Linux debian 4.3.0-1-amd64 #1 SMP Debian 4.3.5-1 (2016-02-06) x86_64 GNU/Linux

**Comment by agnat** [comment]
> ../src/mdns.hpp:32:20: fatal error: dns_sd.h: Aucun fichier ou dossier de ce type

I'm not good with french, but this looks like a "file not found". Please take a look at the installation instructions in the [README](https://github.com/agnat/node_mdns#installation).
