### ISSUE TITLE
Provide method to match local advertisement to discovered service

### ISSUE THREAD

**Issue by ajmas** [agnat/node_mdns#166]
When browsing for services the 'serviceUp' event will also return instances matching the locally started advertisements. It would be useful to have a way to find out if a discovered service is equal to one of the locally started services. I didn't see anything equivalent when I looked through the docs.

I am thinking something along the lines of:

```
if (!service.isSame(myAdvertisements)) {
    // do stuff
}
```

Currently in my own code I have the following, but feel it may still be better if the matching capability was part of the API:

```
    var ad = mdns.createAdvertisement(mdns.tcp('http'), listeningPort, function (error, myService) {

        var localServiceName = myService.name + '.' + myService.domain;

        var browser = mdns.createBrowser(mdns.tcp('http'));

        browser.on('serviceUp', function(service) {
           var serviceName = service.name + '.' + service.replyDomain;
           // Ideally: if (service.isSame((myService)) {
           if (serviceName == localServiceName) {
              console.log('matching host');
           } else {
              console.log('NOT matching host', service.host, os.hostname());
           }
        });

        browser.on('serviceDown', function(service) {
          console.log("service down: ", service);
        });

        browser.start();

    });
```

Failing an API change, what approach would you use to match a local advertisement to a discovered service?

**Comment by agnat** [comment]
Sorry for the late response. I read your proposal multiple times always putting it back on the stack because...

TBH, I'm not convinced. Comparing the name seems simple enough. Just use a local utility function and be like `isSame(service, ad)`.

The approach looks good to me.

**Comment by ajmas** [comment]
At  this point I haven't revisited the issue in a bit and it is not blocking me. If you feel you want close it go on ahead.
