### ISSUE TITLE
in Ubuntu can't installe

### ISSUE THREAD

**Issue by buzai** [agnat/node_mdns#168]
can't find dns_sd_bindings

**Comment by buzai** [comment]
i think u miss a dns_sd.h .
so i can't make mdns right.
in your dns_sd.cpp you include dns_sd.h.
but i can't find it

**Comment by agnat** [comment]
> On 04.06.2016, at 14:27, chenLX <notifications@github.com> wrote:
> 
> i think u miss a dns_sd.h .
> 
Hehe, and I think you are missing dns_sd.h.

Please see the installation instructions in the README.

**Comment by buzai** [comment]
很抱歉，这是我自己的问题，谢谢您的回复，我已经解决了这个问题。
