### ISSUE TITLE
node-gyp rebuild fails even if --unsafe-perm is set for sudo npm install -g

### ISSUE THREAD

**Issue by andig** [agnat/node_mdns#171]
This is the command on raspberry pi2:

    sudo npm install -g --unsafe-perm homebridge

This is the output:

        ...
	> mdns@2.3.3 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns
	> node-gyp rebuild

	make: Entering directory '/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/build'
	  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
	In file included from ../src/dns_sd.cpp:1:0:
	../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
	 #include <dns_sd.h>
	                    ^
	compilation terminated.
	dns_sd_bindings.target.mk:142: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
	make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
	make: Leaving directory '/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/build'
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
	gyp ERR! stack     at emitTwo (events.js:87:13)
	gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
	gyp ERR! System Linux 4.1.21+
	gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns
	gyp ERR! node -v v4.0.0
	gyp ERR! node-gyp -v v3.0.1
	gyp ERR! not ok 

I believe this issue is separate from https://github.com/agnat/node_mdns/issues/164

**Comment by andig** [comment]
Fixed via http://stackoverflow.com/questions/19585117/error-dns-sd-h-no-such-file-or-directory

**Comment by agnat** [comment]
For reference, see the [README](https://github.com/agnat/node_mdns/blob/master/README.md#installation).
