### ISSUE TITLE
Error: node-gyp rebuild` (cant find .hpp/.cpp)

### ISSUE THREAD

**Issue by JustMeDaFaq** [agnat/node_mdns#175]
Hi, 
im trying to install mdns via npm by using:

npm install mdns

(In Windows)
tho getting errored out. 

Console outputs stuff like that:

> c:\new\ionic2app\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "dn
> s_sd.h": No such file or directory (Quelldatei wird kompiliert ..\src\dns_service_ref_deallocate.cpp) [C:\new\ionic2App
> \node_modules\mdns\build\dns_sd_bindings.vcxproj]
> c:\new\ionic2app\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "dn
> s_sd.h": No such file or directory (Quelldatei wird kompiliert ..\src\mdns_utils.cpp) [C:\new\ionic2App\node_modules\md
> ns\build\dns_sd_bindings.vcxproj]
> c:\new\ionic2app\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "dn
> s_sd.h": No such file or directory (Quelldatei wird kompiliert ..\src\dns_service_resolve.cpp) [C:\new\ionic2App\node_m
> odules\mdns\build\dns_sd_bindings.vcxproj]
>   socket_watcher.cpp
>   txt_record_ref.cpp
>   txt_record_create.cpp
>   txt_record_deallocate.cpp

Ive also attached the log file
[npm-debug.txt](https://github.com/agnat/node_mdns/files/453295/npm-debug.txt)

**Comment by agnat** [comment]
Please see the [README](https://github.com/agnat/node_mdns#installation).

**Comment by JustMeDaFaq** [comment]
i did install Bonjour, it does happen anyway. So reading the readme wont help me actually.

**Comment by agnat** [comment]
Well, the missing file `dns_sd.h` is part of the bonjour distribution and it works if the `BONJOUR_SDK_HOME` environment variable is set ... like the README says. If it doesn't your bonjour SDK installation is broken.

**Comment by JustMeDaFaq** [comment]
I already set the environment variable for bonjour like that:

set BONJOUR_SDK_HOME = C:\Program Files\Bonjour SDK\

Thats correct?

**Comment by agnat** [comment]
No. You don't have to set it manually. The SDK installer does that already.

**Comment by JustMeDaFaq** [comment]
The SDK installer doesnt set the environment variable - at least for me.
Probably a windows 10 problem? Dont know.  Thanks anyway.
Il try to google the default environment path

**Comment by JustMeDaFaq** [comment]
Was able to sort it out by manually setting the variable, thanks for your work and help! :)

I
