### ISSUE TITLE
Installing mdns on Synology, node-gyp rebuild fails.

### ISSUE THREAD

**Issue by woutercoppens** [agnat/node_mdns#180]
I have installed node.js via optware-ng. When I try to install homebridge, I get the following error:

` npm install -g --unsafe-perm homebridge
/volume1/@optware/bin/homebridge -> /volume1/@optware/lib/node_modules/homebridge/bin/homebridge

> mdns@2.3.3 install /volume1/@optware/lib/node_modules/homebridge/node_modules/mdns
> node-gyp rebuild

make: Entering directory /volume1/@optware/lib/node_modules/homebridge/node_modules/mdns/build
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_browse.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_get_addr_info.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_process_result.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_sock_fd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_register.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_resolve.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_update_record.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/mdns_utils.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/network_interface.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/socket_watcher.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_create.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_set_value.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_get_length.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_buffer_to_object.o
  SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node
/opt/bin/ld: cannot find -ldns_sd
collect2: error: ld returned 1 exit status
dns_sd_bindings.target.mk:184: recipe for target 'Release/obj.target/dns_sd_bindings.node' failed
make: *** [Release/obj.target/dns_sd_bindings.node] Error 1
make: Leaving directory '/volume1/@optware/lib/node_modules/homebridge/node_modules/mdns/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/volume1/@optware/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.2.40
gyp ERR! command "/volume1/@optware/bin/node" "/volume1/@optware/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/@optware/lib/node_modules/homebridge/node_modules/mdns
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
/volume1/@optware/lib
└── (empty)

npm ERR! Linux 3.2.40
npm ERR! argv "/volume1/@optware/bin/node" "/opt/bin/npm" "install" "-g" "--unsafe-perm" "homebridge"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1`

Before I had an error because dns_sd.h was not found, but I copied that file from the avahi sources into /opt/include.

Thx,

Wouter

PS: I know there is a docker image available with homebridge configured, but my synology nas doesn't support docker.

**Comment by agnat** [comment]
> [...] but I copied that file from the avahi sources into /opt/include

Really? You started tampering with a source packages and header files and opened an issue _before_ looking at the [README](https://github.com/agnat/node_mdns#installation). Well...

**Comment by rngtng** [comment]
@woutercoppens any luck?

**Comment by woutercoppens** [comment]
@rngtng I stopped trying to use homebridge as it was Apple only. I'm now playing with https://home-assistant.io/

**Comment by rngtng** [comment]
@woutercoppens good to know thx, but it doesn't look like having homekit/siri support :(
