### ISSUE TITLE
Cannot install mdns in Windows 10

### ISSUE THREAD

**Issue by KytechN24** [agnat/node_mdns#184]
I am unable to install mdns 2.3.3 on Windows 10 x64 using npm and my current configuration.
node version: 6.2.2
npm version: 3.9.5
Compiler: Visual Studio 2015 Community
Python Version: 2.7
Bonjour SDK version: 3.0

-- npm-debug.log --
273 error Windows_NT 10.0.14393
274 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mdns"
275 error node v6.2.2
276 error npm  v3.9.5
277 error code ELIFECYCLE
278 error mdns@2.3.3 install: `node-gyp rebuild`
278 error Exit status 1
279 error Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
279 error Make sure you have the latest version of node.js and npm installed.
279 error If you do, this is most likely a problem with the mdns package,
279 error not with npm itself.
279 error Tell the author that this fails on your system:
279 error     node-gyp rebuild
279 error You can get information on how to open an issue for this project with:
279 error     npm bugs mdns
279 error Or if that isn't available, you can get their info via:
279 error     npm owner ls mdns
279 error There is likely additional logging output above.
280 verbose exit [ 1, true ]

**Comment by KytechN24** [comment]
I was able to get this to work after messing around with the build settings so that it pointed to the proper MSVC version. It's working great now!

**Comment by hugohil** [comment]
Hi @Kytech ! Could you provide more details on how you manage to get this to work please ? I'm facing the same issue with `electron-rebuild`. Config is pretty much the same. Thanks!

**Comment by Kytech** [comment]
@hugohil, run ```npm config set msvs_version 2013 --global``` , replacing 2013 with whatever version of MSVC you have installed. This is what fixed the issue on my system. If that doesn't work, try running npm install in the Visual Studio Command Prompt. If neither of those work, try running ```npm install --msvs_version=2013 mdns``` , replacing 2013 with your version of MSVC.
