### ISSUE TITLE
alternative API for DNSServiceGetAddrInfo() 

### ISSUE THREAD

**Issue by amalpj** [agnat/node_mdns#186]
I am trying to port bonjure related code to linux using avahi compatable libraries , but I could not find the definition for DNSServiceGetAddrInfo(), Is there any alternative way for replace  DNSServiceGetAddrInfo() call from source code ?

**Comment by agnat** [comment]
That's right. The avahi compat library does not implement DNSServiceGetAddrInfo(). Just use the OS function getaddrinfo(). On every modern Linux this will trigger a bonjour lookup via the nameservice switch.

HTH
