### ISSUE TITLE
ERROR Module Version Mismatch

### ISSUE THREAD

**Issue by cunnagin** [agnat/node_mdns#190]
Just wanted to note this for other users (sounds like some of the issues folks had using with Electron).  I use in a Meteor app and if my node version is >4.8.3 and I 'npm install mdns' it builds but does not work (I get the 'module version mismatch using 48 expected 46' ...) error. I had to add the package while using node version 4.8.3 (so mdns was built under that environment) then it worked and I could change to a newer node version for running my app and it remained working.

**Comment by cunnagin** [comment]
If there is something in the source code that is looking for a specific version of node during build could that be changed in order to let the module build under newer node versions? Unless I'm way off base and it has to do with my Meteor app side.

**Comment by agnat** [comment]
> If there is something in the source code that is looking for a specific version of node [...]

Well, all native node add-ons do this. It's build into node core. If you get a module version mismatch you have to recompile.

Closing.
