### ISSUE TITLE
Problem building mdns

### ISSUE THREAD

**Issue by jneroes** [agnat/node_mdns#191]
Hi,
i have problems to build mdns. It worked till the last update of the homebridge package.
And now im not able to build it and get the following error message.

`> mdns@2.3.3 install /home/pi/node_modules/mdns
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/roo                                                                                                 t/.node-gyp/6.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/node_m                                                                                                 odules/mdns/.node-gyp"
make: Entering directory '/home/pi/node_modules/mdns/build'
/usr/bin/printf: 1: /usr/bin/printf: Syntax error: word unexpected (expecting ")                                                                                                 ")
dns_sd_bindings.target.mk:149: recipe for target 'Release/obj.target/dns_sd_bind                                                                                                 ings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 2
make: Leaving directory '/home/pi/node_modules/mdns/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_                                                                                                 modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                                                                                 s.js:215:12)
gyp ERR! System Linux 4.4.50-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_mod                                                                                                 ules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/mdns
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mdns"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
`

Thanks Soeren

**Comment by larsenglund** [comment]
Hi, I think I had the same problem after updating node.js to the latest version and solved it by installing newer versions of gcc and g++ as described here: https://stackoverflow.com/questions/40470973/error-this-version-of-node-nan-v8-requires-a-c11-compiler

Sample of my error output:
```
...<snip>...
dns_sd_bindings.target.mk:149: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/mdns/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.1.19-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/mdns
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-05-27T20_47_05_405Z-debug.log


...<snip>...
416 warn mdns_server@1.0.0 No repository field.
417 verbose stack Error: mdns@2.3.3 install: `node-gyp rebuild`
417 verbose stack Exit status 1
417 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
417 verbose stack     at emitTwo (events.js:106:13)
417 verbose stack     at EventEmitter.emit (events.js:194:7)
417 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
417 verbose stack     at emitTwo (events.js:106:13)
417 verbose stack     at ChildProcess.emit (events.js:194:7)
417 verbose stack     at maybeClose (internal/child_process.js:899:16)
417 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
418 verbose pkgid mdns@2.3.3
419 verbose cwd /home/pi/node/server
420 verbose Linux 4.1.19-v7+
421 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "mdns"
422 verbose node v7.10.0
423 verbose npm  v4.6.1
424 error code ELIFECYCLE
425 error errno 1
426 error mdns@2.3.3 install: `node-gyp rebuild`
426 error Exit status 1
427 error Failed at the mdns@2.3.3 install script.
427 error This is probably not a problem with npm. There is likely additional logging output above.
428 verbose exit [ 1, true ]
```
