### ISSUE TITLE
Do this pkg works on a web browser with browserify?

### ISSUE THREAD

**Issue by blanchma** [agnat/node_mdns#196]
I want to publish/discover services from a browser (bonjour services) running on mobile apps. Should this pkg support running in a web browser?

**Comment by dsamarin** [comment]
I don't think that's possible. This package uses native code to interface with Bonjour/Avahi. Also technically to be able to publish services, you need to create an mDNS server on port 5353 which isn't possible in a browser with normal browser APIs.

**Comment by ronkorving** [comment]
Indeed. This does not work in browsers. Your best bet is to do service discovery from a server (if you have one sitting around already) and have that serve up results to your web interface.
