### ISSUE TITLE
i stall not unserstand how to use this module

### ISSUE THREAD

**Issue by 748890753yiyi** [agnat/node_mdns#212]
like this:
1.var mdns = require('mdns')
,express = require('express');
var app = express();
app.get('/', function(req, res){
res.send('Hello World');
});

var listener = app.listen(4321, function() {
console.log('Listening on port', 4321);
ad = mdns.createAdvertisement(mdns.tcp('http'), 4321);
ad.start();
});

2.var mdns = require("mdns");
var browser = mdns.createBrowser(mdns.tcp('http'));
browser.on('serviceUp', function(service) {
console.log("service up: ", service);
});
browser.on('serviceDown', function(service) {
console.log("service down: ", service);
});
browser.start();

3.express http server output:
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
Listening on port 4321

4.mdns server output:
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister

5.have no service output, and i don`t konw the user guide "Before we begin go to the internet and get you a bonjour browser so that you can ALL the service discovery." to tell me what should i can do , please tell me how to test two server connect , very thanks

6.this is Advertisement console output :
Advertisement {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _watcherStarted: false,
  serviceRef: DNSServiceRef { initialized: true, fd: 14 },
  watcher: SocketWatcher { host: [Circular], callback: [Function] } }

7.this is browser console output:
Browser {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _watcherStarted: false,
  serviceRef: DNSServiceRef { initialized: true, fd: 13 },
  watcher: SocketWatcher { host: [Circular], callback: [Function] } }

**Comment by agnat** [comment]
1. The code is hard to read but that looks better
1. Look at how other applications do it by looking at [dependent modules](https://www.npmjs.com/browse/depended/mdns)
1. A bonjour browser is a third party application that displays all bonjour services. It helps with debugging. You should see your advertisement.
1. I'm sorry, but I'm not going to debug this further since it is probably a local issue (networking, firewall, etc.)

**Comment by 748890753yiyi** [comment]
thank you , i run on the virtual machine is bad , but run in the true machine well , i think the reason is my virtual environment;
now is ok, thank you vary much.
