### ISSUE TITLE
Failure on Raspberry Pi: getaddrinfo -3001

### ISSUE THREAD

**Issue by dustinbolton** [agnat/node_mdns#235]
I am trying to use this on a Raspberry Pi (Raspbian GNU/Linux 8.0 (jessie); Linux raspberrypi 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux; Node v8.9.3) with no success. I just get a "getaddrinfo -3001" error.  I'm just looking for Google Chromecast devices. The same code works fine on my Macbook Pro.

Device is connected via ethernet and on the same network as the devices I'm browsing for.

`
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

Error: getaddrinfo -3001
    at errnoException (/home/pi/Documents/node/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/home/pi/Documents/node/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/home/pi/Documents/node/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
`

Code:
`var mdns = require('mdns');

var browser = mdns.createBrowser(mdns.tcp('googlecast'));
var livingRoomChromecast;
browser.on('serviceUp', function(service) {
	console.log('Found Chromecast "%s" at %s:%d', service.name, service.addresses[0], service.port);
});
browser.start();`

**Comment by dustinbolton** [comment]
UPDATE: I discovered that while this has a different error, it's caused by the same issue at https://github.com/agnat/node_mdns/issues/130

Modifying /node_modules/msdns/lib/browser.js Browser.defaultResolverSequence to:
`
Browser.defaultResolverSequence = [
  rst.DNSServiceResolve()
, 'DNSServiceGetAddrInfo' in dns_sd ? rst.DNSServiceGetAddrInfo() : rst.getaddrinfo({families:[0]})
, rst.makeAddressesUnique()
];
`
fixed the issue.

The change that fixes it is adding "{families:[0]}" to the rst.getaddrinfo() call.

**Comment by agnat** [comment]
Yes, that's a known issue and disabling IPv6 is the right thing to do. You don't have to modify the package, however. Just use a custom resolver sequence:

http://agnat.github.io/node_mdns/user_guide.html#resolver_sequence

I hope this helps...

**Comment by nleclerc** [comment]
Sorry but there doesn't seem to be a way to override the resolverSequence when you create an advertisement. Only reference i see in the code are in the browser.
Using v2.5.1 btw.

**Comment by agnat** [comment]
That‘s correct. Advertisements don‘t use the resolver chain because they are not concerned with IP addresses. That’s the browsers job.

**Comment by nleclerc** [comment]
Well, i still got that error :
`*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
(node:7049) UnhandledPromiseRejectionWarning: Error: getaddrinfo -3001
    at errnoException (/home/escapeserver/escapeserver/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/home/escapeserver/escapeserver/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/home/escapeserver/escapeserver/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)`

and my code:

`actualType = mdns.tcp(config.local.mdns.type)
	ad = mdns.createAdvertisement actualType, config.env.listenPort
	ad.start()`

**Comment by nleclerc** [comment]
after doing some testing i remembered that my app also browses for servers... my bad. Sorry.
