### ISSUE TITLE
Unable to install on macos monterey

### ISSUE THREAD

**Issue by nleclerc** [agnat/node_mdns#257]
Current build is still dependent on python 2 so it won't build on monterey since it only provides python 3.
Not sure what the path forward is.

In the meantime a workaround is to install python 2.
(found it on https://www.alfredapp.com/help/kb/python-2-monterey/)

Using homebrew you can install pyenv
`brew install pyenv`
Then install the latest python 2
`pyenv install 2.7.18`
and then either link the executable globally
`ln -s "${HOME}/.pyenv/versions/2.7.18/bin/python2.7" "${HOMEBREW_PREFIX}/bin/python"`
or add the following export in your env file
`export PYTHON="${HOME}/.pyenv/versions/2.7.18/bin/python2.7"`

**Comment by agnat** [comment]
Ok, let's see... It would seem your system has an outdated version of the `node-gyp` build tool. It's written in python and it's the only thing I can think of which might trigger the behaviour described. Fortunately, the current version of the tool works fine with python 3. So, I think the right path forward is to update your `node-gyp` installation.

I hope this helps...

**Comment by nleclerc** [comment]
Oh ok, seems like i don't use much dependencies that require rebuilding.
I am using an older node version (12.4.0) because it's an electron app. Guess i'll have to upgrade that.
Thanks.
