### ISSUE TITLE
mdns Install Fails on BeagleBone [missing dns_sd.h]

### ISSUE THREAD

**Issue by AshuJoshi** [agnat/node_mdns#73]
I am trying to install mdns on a BeagleBone to make use of the service. First I ran into a problem with the "npm install mdns" running into a problem with a check on Python version - that was successfully averted thanks to this post [in short per this post - semver.lt fails]: https://groups.google.com/forum/#!msg/beagleboard/-M-xtkMHHk4/lrrazYVloEgJ

I am running into an install problem faced by another user - dependency on the Avahi files [specfically dns_sd.h]. Here is the thread: https://github.com/agnat/node_mdns/issues/60

According to this thread above - I need to get the equivalent of libavahi-compat-libdnssd-dev - I cannot seem to find the equivalent avahi package.

The BeagleBone is running Angstrom Linux: Linux beaglebone 3.8.13 #1 SMP Mon May 20 17:07:58 CEST 2013 armv7l GNU/Linux

I forced install of "avahi-dev" using opkg install but I still get the error reproduced below at the end of the message.

Regards
Ashu

------------------------------------ Error Output --------------------------------

root@beaglebone:/# npm install mdns
npm http GET https://registry.npmjs.org/mdns
npm http 304 https://registry.npmjs.org/mdns

> mdns@1.1.0 install /node_modules/mdns
> node-gyp rebuild

make: Entering directory `/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:31:20: fatal error: dns_sd.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory`/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:256:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Linux 3.8.13
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/mdns
gyp ERR! node -v v0.8.22
gyp ERR! node-gyp -v v0.8.5
gyp ERR! not ok 
npm ERR! mdns@1.1.0 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the mdns@1.1.0 install script.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.13
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "mdns"
npm ERR! cwd /
npm ERR! node -v v0.8.22
npm ERR! npm -v 1.2.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0

**Comment by AAADiver** [comment]
Sorry, I'm a complete noob. I'm trying to solve the same problem on a RPi. I've followed your directions but get hung on "opkg install libssp-dev". It doesn't recognize opkg command. Any recommendations or guidance?

Thx!

**Comment by agnat** [comment]
`opkg` is the package manager of the Angstrom distro. AFAIK, angstrom is not very common on RPI and most distros use `apt-get`, the debian package manager. That said, I doubt you have to compile your own avahi on a modern RPI distro, The system one will do.

**Comment by AAADiver** [comment]
Thanks agnat. Any idea how I could resolve an error where I am missing /src/dns_sd file?

**Comment by agnat** [comment]
No, I don't know anything about `/src/dns_sd`. No such thing. You probably mean `dns_sd.h`? This way please: https://github.com/agnat/node_mdns#installation
